# Generated by Django 2.0 on 2020-05-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('imageUri', models.ImageField(upload_to='players/img')),
                ('jerseyNumber', models.PositiveIntegerField()),
                ('Country', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clubState', models.CharField(max_length=100)),
                ('logoUri', models.ImageField(upload_to='teams/img/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
