# Generated by Django 3.0.6 on 2020-05-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200528_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='imageUri',
            field=models.ImageField(upload_to='media/players/img/'),
        ),
    ]
