# Generated by Django 3.0.5 on 2020-05-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200529_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='teampoints',
            field=models.CharField(max_length=100),
        ),
    ]
